services:
  app:
    build: .
    image: erikvargas/play-with-docker:latest
    volumes:
      - ./credentials:/mnt/s3:ro
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    env_file:
      - .env
    restart: unless-stopped
